services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SuperuserSettings__UserName=admin
      - SuperuserSettings__Password=SuperSecurePassword123!
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=postgres;
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
