services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"